### ISSUE TITLE
where is the path of video when download it

### ISSUE THREAD

**Issue by Abo5** [nightswinger/rubytube#1]
i try this code but when i run it i dont where is the video

```
require 'rubytube'

# Initialize with video URL
video = RubyTube.new('https://www.youtube.com/watch?v=dQw4w9WgXcQ')

# Specify the directory where the video should be saved
download_directory = '/Users/qppn/Desktop/Projects/'

# Download video
video.streams.first.download(output: download_directory)

# Filtering streams
video.streams
  .filter(progressive: true, file_extension: 'mp4')
  .order(resolution: :desc)
  .first
  .download(output: download_directory)
```
and this error show up to me :

```
qppn@MacBook-Pro-Abdullah Projects % ruby "/Users/qppn/Desktop/Projects/download-video.rb"
/Users/qppn/.rvm/gems/ruby-3.2.2/gems/rubytube-0.5.0/lib/rubytube/stream.rb:31:in `download': unknown keyword: :output (ArgumentError)
        from /Users/qppn/Desktop/Projects/download-video.rb:10:in `<main>'
```

because I want specific path to download this [video](https://www.youtube.com/watch?v=dQw4w9WgXcQ) in this file /Users/qppn/Desktop/Projects/

**Comment by nightswinger** [comment]
sorry for lack of examples.
please use `output_dir` instead of `output` as argument.
